### PR TITLE
Extend base event in the TranslationsSaved event.

### LINKED ISSUE #22: Error When Saving
**Expected behavior:**
The package should save translations. This seems to be caused by having the automatic commit feature enabled.

**Actual behavior:**
A server error is thrown and the translations are not saved.

**Reproduce steps:**

**Version:**
1.4.0

**Additional Information:**
Added the error below:
```
[2024-01-30 15:45:32] production.ERROR: Undefined property: RyanMitchell\StatamicTranslationManager\Events\TranslationsSaved::$authenticatedUser {"userId":"29f0a0df-5bd6-4501-aa03-df5a71178a64","exception":"[object] (ErrorException(code: 0): Undefined property: RyanMitchell\\StatamicTranslationManager\\Events\\TranslationsSaved::$authenticatedUser at /home/forge/pelorus-travel.strattons.com/vendor/statamic/cms/src/Git/Subscriber.php:39)
[stacktrace]
```

### PR DESCRIPTION
**Pull request by DanielDarrenJones**
Fixes https://github.com/ryanmitchell/statamic-translation-manager/issues/22

### CODE REVIEW

**Comment by DanielDarrenJones** [comment]
@ryanmitchell This doesn't actually seem to be working as expected, the error had gone and it showed as saved, but when the page is refreshed the value isn't actually being saved as shown in the loom below:

https://www.loom.com/share/82537676c763448cbec6d7afc422ae5f

**Comment by ryanmitchell** [comment]
I would suggest turning your git integration off and seeing if it works then. I can’t think of anything else that would causing it not to save.

**Comment by DanielDarrenJones** [comment]
Unfortunately, we can't do that for this project. I will have to try and track down the issue.

**Comment by DanielDarrenJones** [comment]
@ryanmitchell it looks like this actually committed the update under the hood to the lang files, but the value shown on the CP seems to be being cached and holding the old value - is there anywhere you can think of that would be caching this and I can investigate further?

**Comment by ryanmitchell** [comment]
Hmm we are telling Sushi not to cache the values in the Translation model, so it shouldn't be doing that.

**Pull request merged**
